x=linspace(-1,1,11);
xext=linspace(-1,1,101);
y=1./(1.+12.*x.^2);
yext=1./(1.+12.*xext.^2);
plot(x,y,'@')
hold on
plot(xext,polyval(polyfit(x,y,1),xext)...
     ,xext,polyval(polyfit(x,y,2),xext)...
     ,xext,polyval(polyfit(x,y,4),xext)...
     ,xext,polyval(polyfit(x,y,6),xext)...
     ,xext,polyval(polyfit(x,y,8),xext)...
     ,xext,polyval(polyfit(x,y,10),xext))
legend('off')
hold off
figure(2)
plot(xext,abs(yext-polyval(polyfit(x,y,1),xext)),...
     xext,abs(yext-polyval(polyfit(x,y,2),xext)),...
     xext,abs(yext-polyval(polyfit(x,y,4),xext)),...
     xext,abs(yext-polyval(polyfit(x,y,6),xext)),...
     xext,abs(yext-polyval(polyfit(x,y,8),xext)),...
     xext,abs(yext-polyval(polyfit(x,y,10),xext)))
legend('off')
